# Generated by Django 5.2.5 on 2025-11-02 16:25

import django.db.models.deletion
import lead_magnets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.CharField(blank=True, max_length=120)),
                ('asset_type', models.CharField(choices=[('logo', 'Logo'), ('image', 'Image')], max_length=20)),
                ('file', models.FileField(upload_to=lead_magnets.models.brand_asset_upload_to)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FirmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=255)),
                ('work_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('firm_website', models.URLField(blank=True)),
                ('firm_size', models.CharField(choices=[('1-2', '1–2'), ('3-5', '3–5'), ('6-10', '6–10'), ('11+', '11+')], max_length=10)),
                ('industry_specialties', models.JSONField(blank=True, default=list)),
                ('logo', models.FileField(blank=True, null=True, upload_to='firm_logos/')),
                ('primary_brand_color', models.CharField(blank=True, max_length=7)),
                ('secondary_brand_color', models.CharField(blank=True, max_length=7)),
                ('preferred_font_style', models.CharField(choices=[('modern-sans', 'Modern Sans-Serif'), ('classic-serif', 'Classic Serif'), ('creative', 'Creative/Display'), ('no-preference', 'No Preference')], default='no-preference', max_length=20)),
                ('branding_guidelines', models.TextField(blank=True)),
                ('preferred_cover_image', models.FileField(blank=True, null=True, upload_to='cover_images/')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firm_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Firm Profile',
                'verbose_name_plural': 'Firm Profiles',
            },
        ),
        migrations.CreateModel(
            name='LeadMagnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='lead_magnets/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_magnets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead_magnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='lead_magnets.leadmagnet')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('lead_magnet', 'email')},
            },
        ),
        migrations.CreateModel(
            name='FormaAIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.JSONField(default=list)),
                ('user_answers', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
                ('lead_magnet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to='lead_magnets.leadmagnet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='lead_magnets.lead')),
                ('lead_magnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='lead_magnets.leadmagnet')),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadMagnetGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_magnet_type', models.CharField(choices=[('guide', 'Guide'), ('case-study', 'Case Study'), ('checklist', 'Checklist'), ('roi-calculator', 'ROI Calculator'), ('trends-report', 'Trends Report'), ('onboarding-flow', 'Client Onboarding Flow'), ('design-portfolio', 'Design Portfolio'), ('custom', 'Custom')], max_length=30)),
                ('main_topic', models.CharField(choices=[('sustainable-architecture', 'Sustainable Architecture'), ('smart-homes', 'Smart Homes'), ('adaptive-reuse', 'Adaptive Reuse'), ('wellness-biophilic', 'Wellness/Biophilic'), ('modular-prefab', 'Modular/Prefab'), ('urban-placemaking', 'Urban Placemaking'), ('passive-house', 'Passive House/Net-Zero'), ('climate-resilient', 'Climate-Resilient'), ('project-roi', 'Project ROI'), ('branding-differentiation', 'Branding & Differentiation'), ('custom', 'Custom')], max_length=50)),
                ('target_audience', models.JSONField(default=list)),
                ('audience_pain_points', models.JSONField(default=list)),
                ('desired_outcome', models.TextField()),
                ('call_to_action', models.CharField(max_length=255)),
                ('special_requests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead_magnet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generation_data', to='lead_magnets.leadmagnet')),
            ],
            options={
                'verbose_name': 'Lead Magnet Generation',
                'verbose_name_plural': 'Lead Magnet Generations',
            },
        ),
        migrations.CreateModel(
            name='TemplateSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=255)),
                ('template_name', models.CharField(max_length=255)),
                ('template_thumbnail', models.URLField(blank=True)),
                ('captured_answers', models.JSONField(default=dict)),
                ('source', models.CharField(choices=[('create-lead-magnet', 'Create Lead Magnet'), ('forma-ai', 'Forma AI')], max_length=30)),
                ('ai_generated_content', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('template-selected', 'Template Selected'), ('content-generated', 'Content Generated'), ('preview-ready', 'Preview Ready'), ('pdf-generated', 'PDF Generated')], default='template-selected', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_magnet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template_selection', to='lead_magnets.leadmagnet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
