# Generated by Django 5.0.2 on 2025-09-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_magnets', '0001_initial'),
    ]

    operations = [
    ]
