# Generated by Django 5.0.2 on 2025-09-24 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_magnets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=255)),
                ('work_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('firm_website', models.URLField(blank=True)),
                ('firm_size', models.CharField(choices=[('1-2', '1–2'), ('3-5', '3–5'), ('6-10', '6–10'), ('11+', '11+')], max_length=10)),
                ('industry_specialties', models.JSONField(blank=True, default=list)),
                ('logo', models.FileField(blank=True, null=True, upload_to='firm_logos/')),
                ('primary_brand_color', models.CharField(blank=True, max_length=7)),
                ('secondary_brand_color', models.CharField(blank=True, max_length=7)),
                ('preferred_font_style', models.CharField(choices=[('modern-sans', 'Modern Sans-Serif'), ('classic-serif', 'Classic Serif'), ('creative', 'Creative/Display'), ('no-preference', 'No Preference')], default='no-preference', max_length=20)),
                ('branding_guidelines', models.TextField(blank=True)),
                ('preferred_cover_image', models.FileField(blank=True, null=True, upload_to='cover_images/')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firm_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Firm Profile',
                'verbose_name_plural': 'Firm Profiles',
            },
        ),
        migrations.CreateModel(
            name='LeadMagnetGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_magnet_type', models.CharField(choices=[('guide', 'Guide'), ('case-study', 'Case Study'), ('checklist', 'Checklist'), ('roi-calculator', 'ROI Calculator'), ('trends-report', 'Trends Report'), ('onboarding-flow', 'Client Onboarding Flow'), ('design-portfolio', 'Design Portfolio'), ('custom', 'Custom')], max_length=30)),
                ('main_topic', models.CharField(choices=[('sustainable-architecture', 'Sustainable Architecture'), ('smart-homes', 'Smart Homes'), ('adaptive-reuse', 'Adaptive Reuse'), ('wellness-biophilic', 'Wellness/Biophilic'), ('modular-prefab', 'Modular/Prefab'), ('urban-placemaking', 'Urban Placemaking'), ('passive-house', 'Passive House/Net-Zero'), ('climate-resilient', 'Climate-Resilient'), ('project-roi', 'Project ROI'), ('branding-differentiation', 'Branding & Differentiation'), ('custom', 'Custom')], max_length=50)),
                ('target_audience', models.JSONField(default=list)),
                ('audience_pain_points', models.JSONField(default=list)),
                ('desired_outcome', models.TextField()),
                ('call_to_action', models.CharField(max_length=255)),
                ('special_requests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead_magnet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generation_data', to='lead_magnets.leadmagnet')),
            ],
            options={
                'verbose_name': 'Lead Magnet Generation',
                'verbose_name_plural': 'Lead Magnet Generations',
            },
        ),
    ]
