# Generated by Django 5.2.5 on 2025-11-14 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_magnets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('brand_assets_missing', 'Brand Assets Missing'), ('image_requirements_unmet', 'Image Requirements Unmet')], max_length=50)),
                ('source', models.CharField(blank=True, max_length=30)),
                ('missing_assets', models.JSONField(blank=True, default=list)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead_magnet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_events', to='lead_magnets.leadmagnet')),
                ('template_selection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_events', to='lead_magnets.templateselection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
