# Generated by Django 5.0.2 on 2025-09-30 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_magnets', '0002_firmprofile_leadmagnetgeneration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaAIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.JSONField(default=list)),
                ('user_answers', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_magnet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to='lead_magnets.leadmagnet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=255)),
                ('template_name', models.CharField(max_length=255)),
                ('template_thumbnail', models.URLField(blank=True)),
                ('captured_answers', models.JSONField(default=dict)),
                ('source', models.CharField(choices=[('create-lead-magnet', 'Create Lead Magnet'), ('forma-ai', 'Forma AI')], max_length=30)),
                ('ai_generated_content', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('template-selected', 'Template Selected'), ('content-generated', 'Content Generated'), ('preview-ready', 'Preview Ready'), ('pdf-generated', 'PDF Generated')], default='template-selected', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_magnet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template_selection', to='lead_magnets.leadmagnet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
