# Generated by Django 5.2.5 on 2025-11-14 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_magnets', '0002_validationevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='validationevent',
            name='event_type',
            field=models.CharField(choices=[('brand_assets_missing', 'Brand Assets Missing'), ('image_requirements_unmet', 'Image Requirements Unmet'), ('title_description_invalid', 'Title Description Invalid')], max_length=50),
        ),
        migrations.CreateModel(
            name='LeadMagnetAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('pdf_generated', 'PDF Generated'), ('sync_leads', 'Sync Leads'), ('create', 'Create Lead Magnet'), ('update', 'Update Lead Magnet')], max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead_magnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='lead_magnets.leadmagnet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_magnet_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
