# Generated by Django 5.2.5 on 2025-12-02 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_magnets', '0003_lead_last_pdf_generated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validationevent',
            name='lead_magnet',
        ),
        migrations.RemoveField(
            model_name='validationevent',
            name='template_selection',
        ),
        migrations.RemoveField(
            model_name='validationevent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='last_pdf_generated_at',
        ),
        migrations.DeleteModel(
            name='LeadMagnetAuditLog',
        ),
        migrations.DeleteModel(
            name='ValidationEvent',
        ),
    ]
