# Generated by Django 5.2.5 on 2025-12-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_magnets', '0005_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateselection',
            name='image_upload_preference',
            field=models.CharField(default='no', max_length=3),
        ),
    ]
