# Generated by Django 6.0.2 on 2026-02-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_magnets', '0006_templateselection_image_upload_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadmagnet',
            name='generation_progress',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
